FROM registry.access.redhat.com/ubi9/ubi-micro:9.6

# Copy the model files in multiple layers to avoid large image issues
COPY models/*.json /models/
COPY models/*.jinja /models/
COPY models/model.safetensors /models/

# Set the user to 1001
USER 1001
